#!/bin/sh

bunx pegjs \
  -o src/lib/generated/csv-parser.js \
  src/lib/csv.pegjs

bunx pegjs \
  -o src/generated/gloss-parser.js \
  --allowed-start-rules GlossWithImplicitLiterals,GlossWithImplicitPointers \
  src/gloss.pegjs

bunx pegjs \
  -o src/generated/generator-rule-parser.js \
  src/generator-rule.pegjs